namespace Fabulous.AST.Build

open System
open System.IO
open System.Security.Cryptography
open System.Text

module HashUtils =

    /// Compute SHA256 hash of content + config
    let computeHash (jsonContent: string) (configString: string) : string =
        use sha256 = SHA256.Create()
        let combined = jsonContent + "\n---CONFIG---\n" + configString
        let bytes = Encoding.UTF8.GetBytes(combined)
        let hashBytes = sha256.ComputeHash(bytes)
        BitConverter.ToString(hashBytes).Replace("-", "").ToLowerInvariant()

    /// Check if regeneration is needed based on hash in an existing file
    let needsRegeneration (outputPath: string) (newHash: string) : bool =
        if not(File.Exists(outputPath)) then
            true
        else
            try
                use reader = new StreamReader(outputPath)
                let firstLine = reader.ReadLine()

                match firstLine with
                | null -> true
                | line when line.StartsWith("// Hash: ") ->
                    let storedHash = line.Substring(9).Trim()
                    storedHash <> newHash
                | _ -> true
            with _ ->
                true

    /// Generate the header comment for output files
    /// Uses source file modification time for deterministic output
    let generateHeader (hash: string) (sourcePath: string) (sourceFullPath: string) : string =
        let timestamp =
            if File.Exists(sourceFullPath) then
                File.GetLastWriteTimeUtc(sourceFullPath).ToString("o")
            else
                DateTime.UtcNow.ToString("o")

        $"// Hash: %s{hash}\n// Generated by Fabulous.AST.Build - DO NOT EDIT\n// Source: %s{sourcePath}\n// Generated: %s{timestamp}\n\n"
